# List of computer scientists

https://en.wikipedia.org/wiki/List_of_computer_scientists

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
from bs4 import BeautifulSoup
import requests
from tqdm import tqdm

pd.set_option('display.max_columns',100)
pd.set_option('display.max_rows',100)

plt.style.use('dark_background')

In [2]:
base_url = 'https://en.wikipedia.org/'
new_url = 'wiki/List_of_computer_scientists'
url = base_url + new_url

response = requests.get(url)

html = response.text
soup = BeautifulSoup(html, 'html.parser')
print(soup.prettify()[:1000])

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available" dir="ltr" lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   List of computer scientists - Wikipedia
  </title>
  <script>
   (function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-w

# Get names and links

In [3]:
links = {}

div = soup.find('div', class_="mw-content-ltr mw-parser-output")
for ul in div.find_all('ul')[:-3]:
    try:
        for li in ul.find_all("li")[:5]:
            a = li.find('a')
            href = a['href']
            links[a.text] = href
        # end
    except:
        1
    # end
# end

# Scrape individual pages

In [4]:
count = 0
cs_data = {}
for k, v in tqdm(links.items(), ncols=50):
    #print(k)
    new_url = v
    url = base_url + new_url
    response = requests.get(url)
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')

    info = {}
    data = soup.find('table', class_="infobox biography vcard")
    try:
        for tr in data.find_all('tr'):
            try:
                a = tr.find('th').text
                
                #b = tr.find('td').text

                b = []
                sp = tr.find('td').find_all("span")
                if len(sp)>0:
                    b += [ item.text for item in sp ]
                    #b = ",".join(b)
                
                #"""
                li = tr.find('td').find_all("li")
                if len(li)>0:
                    b += [ item.text for item in li ]
                    #b = ",".join(b)
                
                href = tr.find('td').find_all("a")
                if len(href)>0:
                    b += [ item.text for item in href ]
                    #b = ",".join(b)
                #""";
                
                b = ",".join(b)
                
                #print(len(sp),len(li),len(href))
                info[a] = b
            except:
                1
            # end
        # end
        count += 1
    except:
        1
    # end
    cs_data[k] = info

    #if count >= 20:
        #break
# end

100%|███████████| 116/116 [00:42<00:00,  2.75it/s]

# Clean columns

In [17]:
df = pd.DataFrame(cs_data).T

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 116 entries, Wil van der Aalst to Hussein Zedan
Data columns (total 42 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Born                     95 non-null     object
 1   Nationality              32 non-null     object
 2   Known for                68 non-null     object
 3   Fields                   73 non-null     object
 4   Institutions             78 non-null     object
 5   Thesis                   41 non-null     object
 6   Doctoral advisor         53 non-null     object
 7   Website                  32 non-null     object
 8   Alma mater               63 non-null     object
 9   Spouse                   15 non-null     object
 10  Awards                   56 non-null     object
 11  Doctoral students        26 non-null     object
 12  Citizenship              13 non-null     object
 13  Died                     28 non-null     object
 14  Children                 9 non-null      object
 15  Relatives                2 non-null      object
 16  Education                29 non-null     object
 17  Spouses                  2 non-null      object
 18  Employer                 3 non-null      object
 19  Occupation               11 non-null     object
 20  Employer(s)              2 non-null      object
 21  Other names              2 non-null      object
 22  Other academic advisors  2 non-null      object
 23  Alma mater               3 non-null      object
 24  Era                      1 non-null      object
 25  Discipline               3 non-null      object
 26  Sub-discipline           1 non-null      object
 27  Notable ideas            1 non-null      object
 28  Academic advisors        3 non-null      object
 29  Parent(s)                1 non-null      object
 30  Occupation(s)            6 non-null      object
 31  Notable credit(s)        1 non-null      object
 32  Years active             1 non-null      object
 33  Organization             1 non-null      object
 34  Notable work             1 non-null      object
 35  Notable students         3 non-null      object
 36  Occupations              1 non-null      object
 37  Organizations            1 non-null      object
 38  Chinese                  1 non-null      object
 39  Transcriptions           1 non-null      object
 40  Hanyu Pinyin             1 non-null      object
 41  Wade–Giles               1 non-null      object
dtypes: object(42)
memory usage: 39.0+ KB

,Born,Nationality,Known for,Fields,Institutions,Thesis,Doctoral advisor,Website,Alma mater,Spouse,Awards,Doctoral students,Citizenship,Died,Children,Relatives,Education,Spouses,Employer,Occupation,Employer(s),Other names,Other academic advisors,Alma mater,Era,Discipline,Sub-discipline,Notable ideas,Academic advisors,Parent(s),Occupation(s),Notable credit(s),Years active,Organization,Notable work,Notable students,Occupations,Organizations,Chinese,Transcriptions,Hanyu Pinyin,Wade–Giles
Wil van der Aalst,"(1966-01-29) ,1966-01-29, (age 58),Eersel,Nor...",,"Workflow patterns,YAWL","Information systems,Workflow management,Petri ...",RWTH Aachen University,(1992),"Jaap Wessels,Kees van Hee",http://www.padsweb.rwth-aachen.de/wvdaalst/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Scott Aaronson,"(1981-05-21) ,1981-05-21, (age 43),[,],[,],[1...",American,"Quantum Turing machine with postselection,Alge...","Computational complexity theory,quantum computing","University of Texas at Austin,Massachusetts In...",NaN,Umesh Vazirani,"scottaaronson.blog,www.scottaaronson.com,scott...","Cornell University,University of California, B...",Dana Moshkovitz,"Alan T. Waterman Award,PECASE,Tomassoni–Chises...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rediet Abebe,"Addis Ababa,Ethiopia",NaN,NaN,"artificial intelligence,algorithms,computer sc...","University of California, Berkeley,Harvard Uni...",(2019),Jon M. Kleinberg,"www.cs.cornell.edu/~red/,md4sg.com,www.cs.corn...","Cornell University,University of Cambridge,Har...",NaN,"Andrew Carnegie Fellow (2022),Harvard Society ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hal Abelson,"(1947-04-26) ,1947-04-26, (age 77),[,],[2]",NaN,"[,],[,],Creative Commons,Public Knowledge,Free...","Computer science education,Amorphous computing",Massachusetts Institute of Technology,"(1973),Topologically Distinct Conjugate-Variet...","[,],Dennis Sullivan,[1]","www.csail.mit.edu/person/hal-abelson,,www.csai...","Princeton University (BA),Massachusetts Instit...",NaN,SIGCSE Award for Outstanding Contribution to C...,"[,],[,],[,],Elizabeth Bradley[1],Mitchel Resni...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Serge Abiteboul,"(1953-08-25) ,1953-08-25, (age 71),[,],[4],Paris",French,"[,],[,],[,],Abiteboul-Vianu Theorem[5][6],Data...","[,],Data bases,[2]",INRIA,"(1982),Matching Functions and Disaggregations ...","[,],Seymour Ginsburg,[3]","abiteboul.com,abiteboul.com",University of Southern California,NaN,"[,],citation needed,when?,SIGMOD Edgar F. Codd...",NaN,French,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df.columns = pd.Series(df.columns).apply(
    lambda x: x.replace('\xa0', ' ').strip() if type(x)==str else x
)

In [19]:
for c in df.columns:
    df[c] = df[c].apply(
        lambda x: x.replace('\xa0', ' ').strip() if type(x)==str else x
    )
# end

for c in df.columns[1:]:
    df[c] = df[c].apply(
        lambda x: re.sub(r"\[[\d,]+\]", "", x) if type(x)==str else x
    )
# end

df.head()

,Born,Nationality,Known for,Fields,Institutions,Thesis,Doctoral advisor,Website,Alma mater,Spouse,Awards,Doctoral students,Citizenship,Died,Children,Relatives,Education,Spouses,Employer,Occupation,Employer(s),Other names,Other academic advisors,Alma mater,Era,Discipline,Sub-discipline,Notable ideas,Academic advisors,Parent(s),Occupation(s),Notable credit(s),Years active,Organization,Notable work,Notable students,Occupations,Organizations,Chinese,Transcriptions,Hanyu Pinyin,Wade–Giles
Wil van der Aalst,"(1966-01-29) ,1966-01-29, (age 58),Eersel,Nort...",,"Workflow patterns,YAWL","Information systems,Workflow management,Petri ...",RWTH Aachen University,(1992),"Jaap Wessels,Kees van Hee",http://www.padsweb.rwth-aachen.de/wvdaalst/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Scott Aaronson,"(1981-05-21) ,1981-05-21, (age 43),[,],[,],[1]...",American,"Quantum Turing machine with postselection,Alge...","Computational complexity theory,quantum computing","University of Texas at Austin,Massachusetts In...",NaN,Umesh Vazirani,"scottaaronson.blog,www.scottaaronson.com,scott...","Cornell University,University of California, B...",Dana Moshkovitz,"Alan T. Waterman Award,PECASE,Tomassoni–Chises...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rediet Abebe,"Addis Ababa,Ethiopia",NaN,NaN,"artificial intelligence,algorithms,computer sc...","University of California, Berkeley,Harvard Uni...",(2019),Jon M. Kleinberg,"www.cs.cornell.edu/~red/,md4sg.com,www.cs.corn...","Cornell University,University of Cambridge,Har...",NaN,"Andrew Carnegie Fellow (2022),Harvard Society ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hal Abelson,"(1947-04-26) ,1947-04-26, (age 77),[,],[2]",NaN,",,Creative Commons,Public Knowledge,Free Softw...","Computer science education,Amorphous computing",Massachusetts Institute of Technology,"(1973),Topologically Distinct Conjugate-Variet...",",Dennis Sullivan,","www.csail.mit.edu/person/hal-abelson,,www.csai...","Princeton University (BA),Massachusetts Instit...",NaN,SIGCSE Award for Outstanding Contribution to C...,",,,Elizabeth Bradley,Mitchel Resnick,Latanya S...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Serge Abiteboul,"(1953-08-25) ,1953-08-25, (age 71),[,],[4],Paris",French,",,,Abiteboul-Vianu Theorem,Data on the Web,,,",",Data bases,",INRIA,"(1982),Matching Functions and Disaggregations ...",",Seymour Ginsburg,","abiteboul.com,abiteboul.com",University of Southern California,NaN,",citation needed,when?,SIGMOD Edgar F. Codd In...",NaN,French,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df = df.dropna(thresh=df.shape[0]//4, axis=1)
df = df.dropna(thresh=df.shape[1]//4, axis=0)
df.head()

,Born,Nationality,Known for,Fields,Institutions,Thesis,Doctoral advisor,Website,Alma mater,Awards,Education
Wil van der Aalst,"(1966-01-29) ,1966-01-29, (age 58),Eersel,Nort...",,"Workflow patterns,YAWL","Information systems,Workflow management,Petri ...",RWTH Aachen University,(1992),"Jaap Wessels,Kees van Hee",http://www.padsweb.rwth-aachen.de/wvdaalst/,NaN,NaN,NaN
Scott Aaronson,"(1981-05-21) ,1981-05-21, (age 43),[,],[,],[1]...",American,"Quantum Turing machine with postselection,Alge...","Computational complexity theory,quantum computing","University of Texas at Austin,Massachusetts In...",NaN,Umesh Vazirani,"scottaaronson.blog,www.scottaaronson.com,scott...","Cornell University,University of California, B...","Alan T. Waterman Award,PECASE,Tomassoni–Chises...",NaN
Rediet Abebe,"Addis Ababa,Ethiopia",NaN,NaN,"artificial intelligence,algorithms,computer sc...","University of California, Berkeley,Harvard Uni...",(2019),Jon M. Kleinberg,"www.cs.cornell.edu/~red/,md4sg.com,www.cs.corn...","Cornell University,University of Cambridge,Har...","Andrew Carnegie Fellow (2022),Harvard Society ...",NaN
Hal Abelson,"(1947-04-26) ,1947-04-26, (age 77),[,],[2]",NaN,",,Creative Commons,Public Knowledge,Free Softw...","Computer science education,Amorphous computing",Massachusetts Institute of Technology,"(1973),Topologically Distinct Conjugate-Variet...",",Dennis Sullivan,","www.csail.mit.edu/person/hal-abelson,,www.csai...","Princeton University (BA),Massachusetts Instit...",SIGCSE Award for Outstanding Contribution to C...,NaN
Serge Abiteboul,"(1953-08-25) ,1953-08-25, (age 71),[,],[4],Paris",French,",,,Abiteboul-Vianu Theorem,Data on the Web,,,",",Data bases,",INRIA,"(1982),Matching Functions and Disaggregations ...",",Seymour Ginsburg,","abiteboul.com,abiteboul.com",University of Southern California,",citation needed,when?,SIGMOD Edgar F. Codd In...",NaN

In [21]:
def fix_born(x):
    if type(x)==str:
        y = re.findall(r"\d{4}-\d{2}-\d{2}", x)
        if len(y)>0:
            return y[0]
    # end
    return np.nan
# end

df.Born = df.Born.apply( fix_born )

In [22]:
df.Fields = df.Fields.str.lower()
df['Known for'] = df['Known for'].str.lower()

In [23]:
df['Fields'].str.get_dummies(',').sum().sort_values()

accessible computing                1
web technologies                    1
inequality                          1
informatics                         1
information management              1
information retrieval               1
information systems                 1
information technology              1
logic                               1
machine learning                    1
networking                          1
operating systems                   1
petri nets                          1
human-computer interaction          1
physics                             1
process mining                      1
program analysis                    1
programming                         1
public affairs                      1
quantum computing                   1
simulation                          1
software engineering                1
specification languages             1
statistics                          1
telecommunications                  1
theoretical neuroscience            1
web science                         1
pim                                 1
history of science                  1
hypermedia                          1
health informatics                  1
amorphous computing                 1
applied mathematics                 1
astronomy                           1
complexity                          1
computation                         1
computational complexity theory     1
computational learning theory       1
computer architecture               1
computer languages                  1
computer science education          1
history of computing                1
control theory                      1
data bases                          1
computer security                   1
workflow management                 1
game theory                         1
data science                        1
formal verification                 1
digital health                      1
digital libraries                   1
evolution                           1
distributed computing               1
electronic design automation        1
algorithms                          2
electrical engineering              2
multimedia                          2
education                           2
programming languages               2
computer vision                     2
natural language processing         2
semantic web                        2
theoretical computer science        3
artificial intelligence             8
mathematics                        10
computer science                   47
dtype: int64

In [24]:
df['Known for'].str.get_dummies(',').sum().sort_values()

 our security advocates    1
oblivious transfer         1
off-side rule              1
opencourseware             1
operating systems          1
                          ..
backus–naur form           2
programming languages      2
computer science           2
software engineering       3
algol                      4
Length: 203, dtype: int64